# Generated by Django 5.2.16 on 2026-07-21 09:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("rfid", "RFID 打卡终端"),
                            ("photo", "拍照终端"),
                            ("combined", "复合终端"),
                        ],
                        max_length=16,
                    ),
                ),
                ("secret_encrypted", models.TextField()),
                ("secret_fingerprint", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=64)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="scenes.scene",
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="scenes.spot",
                    ),
                ),
            ],
            options={
                "ordering": ("device_id",),
            },
        ),
        migrations.CreateModel(
            name="DeviceRequestNonce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nonce", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_nonces",
                        to="iot.device",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "nonce"), name="uniq_request_nonce_per_device"
                    )
                ],
            },
        ),
    ]
