<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { ElDrawer } from 'element-plus'
import ConfirmReasonDialog from '../../components/security/ConfirmReasonDialog.vue'
import { forceUnbind, getUser, listUserCards, listUserCheckins, listUserVisits } from '../../services/management/users'
import type { CardBinding } from '../../types/card'
import type { CheckinEvent } from '../../types/dashboard'
import type { ManagementVisitor, VisitSession } from '../../types/user'

const props=defineProps<{modelValue:boolean;userId:string;canEdit:boolean}>(); const emit=defineEmits<{'update:modelValue':[boolean]}>()
const user=ref<ManagementVisitor|null>(null),bindings=ref<CardBinding[]>([]),visits=ref<VisitSession[]>([]),checkins=ref<CheckinEvent[]>([]),loading=ref(false),submitting=ref(false),target=ref<CardBinding|null>(null)
const errors=reactive({user:'',bindings:'',visits:'',checkins:''}); const time=(v:string|null)=>v?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'暂无'
async function loadBindings(){errors.bindings='';try{bindings.value=(await listUserCards(props.userId)).data.items}catch(e){errors.bindings=e instanceof Error?e.message:'绑定记录加载失败'}}
async function load(){if(!props.userId)return;loading.value=true;Object.keys(errors).forEach(k=>errors[k as keyof typeof errors]='');const r=await Promise.allSettled([getUser(props.userId),listUserCards(props.userId),listUserVisits(props.userId),listUserCheckins(props.userId)]);if(r[0].status==='fulfilled')user.value=r[0].value.data;else errors.user=(r[0].reason as Error)?.message||'用户资料加载失败';if(r[1].status==='fulfilled')bindings.value=r[1].value.data.items;else errors.bindings=(r[1].reason as Error)?.message||'绑定记录加载失败';if(r[2].status==='fulfilled')visits.value=r[2].value.data.items;else errors.visits=(r[2].reason as Error)?.message||'游览记录加载失败';if(r[3].status==='fulfilled')checkins.value=r[3].value.data.items;else errors.checkins=(r[3].reason as Error)?.message||'打卡记录加载失败';loading.value=false}
watch([()=>props.modelValue,()=>props.userId],([visible])=>{if(visible)void load()})
async function confirm(payload:{confirm:true;reason:string}){if(!target.value)return;submitting.value=true;try{await forceUnbind(target.value.id,payload);target.value=null;await loadBindings()}finally{submitting.value=false}}
</script>
<template><ElDrawer :model-value="modelValue" title="用户数据链" size="min(720px,94vw)" @close="emit('update:modelValue',false)"><p v-if="loading">正在汇总用户数据…</p><template v-if="user"><header><img v-if="user.avatar_url" :src="user.avatar_url" alt="用户头像"/><span><h2>{{user.nickname||user.username}}</h2><p>@{{user.username}} · {{user.is_demo?'演示用户':'正式用户'}}</p></span></header><p v-if="errors.user" class="error">{{errors.user}}</p><section><h3>卡片绑定</h3><p v-if="errors.bindings" class="error">{{errors.bindings}}</p><p v-else-if="bindings.length===0">暂无绑定记录</p><ul v-else><li v-for="b in bindings" :key="b.id"><span><strong>{{b.card?.serial_no||b.card_id}}</strong><small>{{b.card?.uid_masked}} · {{b.alias||b.bind_method}} · {{b.unbound_at?'已解绑':'当前绑定'}}</small><small v-if="b.unbound_reason">原因：{{b.unbound_reason}}</small></span><button v-if="canEdit&&!b.unbound_at" @click="target=b">强制解绑</button></li></ul></section><section><h3>游览记录</h3><p v-if="errors.visits" class="error">{{errors.visits}}</p><ul v-else><li v-for="v in visits" :key="v.id">{{v.local_date}} · 开始 {{time(v.started_at)}} · 最近打卡 {{time(v.last_checkin_at)}}</li></ul></section><section><h3>最近打卡</h3><p v-if="errors.checkins" class="error">{{errors.checkins}}</p><ul v-else><li v-for="e in checkins" :key="e.id">{{e.event_id}} · {{e.checkin_type.toUpperCase()}} · {{e.status}}</li></ul></section></template></ElDrawer><ConfirmReasonDialog :model-value="Boolean(target)" title="强制解除卡片绑定" description="解绑不会删除历史记录；请填写管理员操作原因。" :submitting="submitting" @update:model-value="!$event&&(target=null)" @confirm="confirm"/></template>
<style scoped>header{display:flex;align-items:center;gap:12px}header img{width:48px;height:48px;border-radius:50%}h2,header p{margin:0}header p,section>p,small{color:var(--tw-color-muted)}section{margin-top:22px;padding-top:14px;border-top:1px solid var(--tw-color-border)}section h3{font-size:14px}ul{display:grid;gap:6px;margin:0;padding:0;list-style:none}li{min-height:42px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px;border-radius:8px;background:#f7f9f7;font-size:11px}li span{display:grid;gap:3px}li button{min-height:34px;border:1px solid #edc2b8;border-radius:7px;background:#fff;color:var(--tw-color-danger);font-weight:700}.error{color:var(--tw-color-danger)}</style>
