# Generated by Django 5.2.16 on 2026-07-21 09:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_profile_cards_and_bindings"),
        ("iot", "0001_initial"),
        ("scenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("local_date", models.DateField()),
                ("started_at", models.DateTimeField()),
                ("last_checkin_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_sessions",
                        to="scenes.scene",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-local_date", "-started_at"),
            },
        ),
        migrations.CreateModel(
            name="CheckinEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.CharField(max_length=128)),
                ("card_uid_hmac", models.CharField(blank=True, max_length=64)),
                (
                    "checkin_type",
                    models.CharField(
                        choices=[("nfc", "NFC"), ("rfid", "RFID"), ("manual_admin", "管理员补录")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "已接受"), ("rejected", "已拒绝")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("device_time", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("result_snapshot", models.JSONField(default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to="accounts.card",
                    ),
                ),
                (
                    "card_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to="accounts.cardbinding",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to="iot.device",
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to="scenes.spot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkin_events",
                        to="visits.visitsession",
                    ),
                ),
            ],
            options={
                "ordering": ("received_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="visitsession",
            constraint=models.UniqueConstraint(
                fields=("user", "scene", "local_date"), name="uniq_daily_visit_per_user_scene"
            ),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(fields=["user", "received_at"], name="checkin_user_received_idx"),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(fields=["card", "received_at"], name="checkin_card_received_idx"),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(fields=["spot", "received_at"], name="checkin_spot_received_idx"),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(
                fields=["device", "received_at"], name="checkin_device_received_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkinevent",
            index=models.Index(
                fields=["visit_session", "status", "received_at"], name="checkin_session_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkinevent",
            constraint=models.UniqueConstraint(
                fields=("device", "event_id"), name="uniq_event_id_per_device"
            ),
        ),
    ]
