<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import PageState from '../components/feedback/PageState.vue'
import OneTimeSecretDialog from '../components/security/OneTimeSecretDialog.vue'
import CardDetailDrawer from '../features/cards/CardDetailDrawer.vue'
import CardFormDrawer from '../features/cards/CardFormDrawer.vue'
import CardImportDialog from '../features/cards/CardImportDialog.vue'
import { createActivationCode, createCard, listCardBindings, listCardCheckins, listCards, updateCard } from '../services/management/cards'
import { useAuthStore } from '../stores/auth'; import { useDisplayStore } from '../stores/display'
import type { Card, CardBinding, CardCheckin, CardCreatePayload } from '../types/card'

const auth=useAuthStore(), display=useDisplayStore(); const cards=ref<Card[]>([]), bindings=ref<CardBinding[]>([]), events=ref<CardCheckin[]>([])
const loading=ref(true), submitting=ref(false), error=ref(''), search=ref(''), status=ref(''); const formOpen=ref(false), importOpen=ref(false), editing=ref<Card|null>(null), detail=ref<Card|null>(null)
const activationCode=ref(''), codeOpen=ref(false); const canEdit=computed(()=>!display.isDemoMode&&auth.can('accounts.change_card')); const statusLabel=(v:string)=>({available:'待绑定',active:'使用中',lost:'已挂失',disabled:'已停用'} as Record<string,string>)[v]??v; const time=(v:string|null)=>v?new Intl.DateTimeFormat('zh-CN').format(new Date(v)):'暂无'
async function load(){loading.value=true;error.value='';try{cards.value=(await listCards({search:search.value,status:status.value,pageSize:100})).data.items}catch(reason){error.value=reason instanceof Error?reason.message:'卡片加载失败'}finally{loading.value=false}}
onMounted(load); function openCreate(){editing.value=null;formOpen.value=true} function openEdit(card:Card){editing.value=card;formOpen.value=true}
async function saveCreate(payload:CardCreatePayload){submitting.value=true;try{await createCard(payload);formOpen.value=false;await load()}finally{submitting.value=false}}
async function saveUpdate(payload:{serial_no:string;status:string}){if(!editing.value)return;submitting.value=true;try{await updateCard(editing.value.id,payload);formOpen.value=false;await load()}finally{submitting.value=false}}
async function openDetail(card:Card){detail.value=card;const results=await Promise.allSettled([listCardBindings(card.id),listCardCheckins(card.id)]);bindings.value=results[0].status==='fulfilled'?results[0].value.data.items:[];events.value=results[1].status==='fulfilled'?results[1].value.data.items:[]}
async function generateCode(card:Card){submitting.value=true;try{activationCode.value=(await createActivationCode(card.id)).data.activation_code;codeOpen.value=true}finally{submitting.value=false}}
</script>
<template><div class="card-page"><header class="title"><div><p>CARD OPERATIONS</p><h1>卡片与激活码</h1><span>卡片 UID 全程脱敏，激活码仅生成后显示一次</span></div><div v-if="canEdit"><button class="secondary" type="button" @click="importOpen=true">批量导入</button><button type="button" @click="openCreate">录入卡片</button></div></header><section class="filters"><input v-model.trim="search" placeholder="卡片编号或 UID 掩码" @keyup.enter="load"/><select v-model="status" @change="load"><option value="">全部状态</option><option value="available">待绑定</option><option value="active">使用中</option><option value="lost">已挂失</option><option value="disabled">已停用</option></select><button class="secondary" type="button" @click="load">查询</button></section><PageState v-if="loading&&cards.length===0" status="loading" title="正在加载卡片"/><PageState v-else-if="error" status="error" :description="error" @retry="load"/><PageState v-else-if="cards.length===0" status="empty" title="暂无符合条件的卡片"/><section v-else class="table-card"><div class="scroll"><table><thead><tr><th>卡片编号</th><th>UID 掩码</th><th>状态</th><th>发放时间</th><th>最后使用</th><th>操作</th></tr></thead><tbody><tr v-for="card in cards" :key="card.id"><td><strong>{{card.serial_no}}</strong></td><td><code>{{card.uid_masked}}</code></td><td>{{statusLabel(card.status)}}</td><td>{{time(card.issued_at)}}</td><td>{{time(card.last_used_at)}}</td><td><div class="actions"><button class="link" @click="openDetail(card)">详情</button><button v-if="canEdit" class="link" @click="openEdit(card)">编辑</button><button v-if="canEdit&&card.status!=='disabled'" data-test="create-activation-code" class="link" :disabled="submitting" @click="generateCode(card)">生成激活码</button></div></td></tr></tbody></table></div></section><CardFormDrawer v-model="formOpen" :card="editing" :submitting="submitting" @create="saveCreate" @update="saveUpdate"/><CardImportDialog v-model="importOpen" @imported="load"/><CardDetailDrawer :model-value="Boolean(detail)" :card="detail" :bindings="bindings" :events="events" @update:model-value="!$event&&(detail=null)"/><OneTimeSecretDialog v-model="codeOpen" label="卡片激活码" :secret="activationCode" @closed="activationCode=''"/></div></template>
<style scoped>.card-page{max-width:1540px;margin:0 auto;padding:26px}.title{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:20px}.title p,.title h1,.title span{margin:0}.title p{color:var(--tw-color-accent);font-size:10px;font-weight:800;letter-spacing:.15em}.title h1{margin:4px 0 6px;font-size:28px}.title span{color:var(--tw-color-muted);font-size:12px}.title>div:last-child{display:flex;gap:9px}button{min-height:40px;padding:0 14px;border:0;border-radius:var(--tw-radius-sm);background:var(--tw-color-primary);color:#fff;font-weight:700}.secondary{border:1px solid var(--tw-color-border);background:#fff;color:var(--tw-color-primary)}.filters{display:flex;gap:9px;margin-bottom:14px;padding:14px;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-md);background:#fff}.filters input,.filters select{min-height:40px;padding:8px 10px;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-sm)}.filters input{min-width:260px}.table-card{overflow:hidden;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-md);background:#fff;box-shadow:var(--tw-shadow-card)}.scroll{overflow-x:auto}table{width:100%;min-width:850px;border-collapse:collapse}th,td{padding:14px 16px;border-bottom:1px solid #edf1ef;text-align:left;font-size:12px}th{background:#f7f9f7;color:var(--tw-color-muted);font-size:10px}.actions{display:flex}.link{min-height:34px;padding:0 6px;background:transparent;color:var(--tw-color-primary);font-size:11px}@media(max-width:700px){.card-page{padding:18px 14px}.title{align-items:flex-start;flex-direction:column}.filters{flex-direction:column}.filters input{min-width:0}}</style>
