<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import PageState from '../components/feedback/PageState.vue'
import UserDetailDrawer from '../features/users/UserDetailDrawer.vue'
import { listUsers } from '../services/management/users'
import { useAuthStore } from '../stores/auth'; import { useDisplayStore } from '../stores/display'
import type { ManagementVisitor } from '../types/user'
const auth=useAuthStore(),display=useDisplayStore();const users=ref<ManagementVisitor[]>([]),loading=ref(true),error=ref(''),search=ref(''),active=ref(''),demo=ref(''),selected=ref<ManagementVisitor|null>(null);const canEdit=computed(()=>!display.isDemoMode&&auth.can('accounts.change_cardbinding'))
async function load(){loading.value=true;error.value='';try{users.value=(await listUsers({search:search.value,isActive:active.value,isDemo:demo.value,pageSize:100})).data.items}catch(e){error.value=e instanceof Error?e.message:'用户加载失败'}finally{loading.value=false}}onMounted(load)
</script>
<template><div class="user-page"><header><div><p>USER OPERATIONS</p><h1>用户与绑定</h1><span>从用户追踪卡片、每日游览和打卡事件</span></div></header><section class="filters"><input v-model.trim="search" placeholder="昵称或用户名" @keyup.enter="load"/><select v-model="active" @change="load"><option value="">全部账号状态</option><option value="true">启用</option><option value="false">停用</option></select><select v-model="demo" @change="load"><option value="">全部用户类型</option><option value="false">正式用户</option><option value="true">演示用户</option></select><button @click="load">查询</button></section><PageState v-if="loading&&users.length===0" status="loading" title="正在加载用户"/><PageState v-else-if="error" status="error" :description="error" @retry="load"/><PageState v-else-if="users.length===0" status="empty" title="暂无符合条件的用户"/><section v-else class="grid"><article v-for="user in users" :key="user.id"><div class="avatar">{{(user.nickname||user.username).slice(0,1)}}</div><div><h2>{{user.nickname||user.username}}</h2><p>@{{user.username}}</p><span :class="{demo:user.is_demo}">{{user.is_demo?'演示用户':'正式用户'}}</span></div><strong>{{user.active_card_count}} 张<small>有效卡片</small></strong><button @click="selected=user">查看数据链</button></article></section><UserDetailDrawer :model-value="Boolean(selected)" :user-id="selected?.id||''" :can-edit="canEdit" @update:model-value="!$event&&(selected=null)"/></div></template>
<style scoped>.user-page{max-width:1540px;margin:0 auto;padding:26px}.user-page>header{margin-bottom:20px}.user-page>header p,.user-page>header h1,.user-page>header span{margin:0}.user-page>header p{color:var(--tw-color-accent);font-size:10px;font-weight:800;letter-spacing:.15em}.user-page>header h1{margin:4px 0 6px;font-size:28px}.user-page>header span{color:var(--tw-color-muted);font-size:12px}.filters{display:flex;gap:9px;margin-bottom:14px;padding:14px;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-md);background:#fff}.filters input,.filters select{min-height:40px;padding:8px 10px;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-sm)}.filters input{min-width:250px}button{min-height:40px;padding:0 13px;border:0;border-radius:var(--tw-radius-sm);background:var(--tw-color-primary);color:#fff;font-weight:700}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}article{display:grid;grid-template-columns:48px 1fr auto auto;align-items:center;gap:13px;padding:18px;border:1px solid var(--tw-color-border);border-radius:var(--tw-radius-md);background:#fff;box-shadow:var(--tw-shadow-card)}.avatar{width:48px;height:48px;display:grid;place-items:center;border-radius:50%;background:var(--tw-color-primary-soft);color:var(--tw-color-primary);font-weight:800}article h2,article p{margin:0}article h2{font-size:15px}article p{margin:3px 0;color:var(--tw-color-muted);font-size:10px}article span{font-size:9px;color:var(--tw-color-primary)}article span.demo{color:var(--tw-color-accent)}article>strong{display:grid;text-align:center}article>strong small{color:var(--tw-color-muted);font-size:9px;font-weight:400}@media(max-width:850px){.grid{grid-template-columns:1fr}}@media(max-width:600px){.user-page{padding:18px 14px}.filters{flex-direction:column}.filters input{min-width:0}article{grid-template-columns:42px 1fr auto}article>button{grid-column:1/-1}}</style>
